// src/lib/languages.js
// 구글 번역(Google Translate)이 공식 지원하는 전체 언어 목록.
// 모든 페이지(Layout.astro, 01-auth, 02-payment)가 이 파일 하나를 공유해서
// 페이지마다 언어 개수가 달라지는 일이 없도록 함.
export const languages = [
  { code: 'en', name: 'English' },
  { code: 'ko', name: '한국어' },
  { code: 'ja', name: '日本語' },
  { code: 'zh-CN', name: '简体中文' },
  { code: 'zh-TW', name: '繁體中文' },
  { code: 'zh-HK', name: '中文（香港）' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'sq', name: 'Shqip' },
  { code: 'am', name: 'አማርኛ' },
  { code: 'ar', name: 'العربية' },
  { code: 'hy', name: 'Հայերեն' },
  { code: 'as', name: 'অসমীয়া' },
  { code: 'ay', name: 'Aymar aru' },
  { code: 'az', name: 'Azərbaycan' },
  { code: 'bm', name: 'Bamanankan' },
  { code: 'eu', name: 'Euskara' },
  { code: 'be', name: 'Беларуская' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'bho', name: 'भोजपुरी' },
  { code: 'bs', name: 'Bosanski' },
  { code: 'bg', name: 'Български' },
  { code: 'ca', name: 'Català' },
  { code: 'ceb', name: 'Cebuano' },
  { code: 'co', name: 'Corsu' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'cs', name: 'Čeština' },
  { code: 'da', name: 'Dansk' },
  { code: 'dv', name: 'ދިވެހި' },
  { code: 'doi', name: 'डोगरी' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'et', name: 'Eesti' },
  { code: 'ee', name: 'Eʋegbe' },
  { code: 'tl', name: 'Filipino' },
  { code: 'fi', name: 'Suomi' },
  { code: 'fr', name: 'Français' },
  { code: 'fy', name: 'Frysk' },
  { code: 'gl', name: 'Galego' },
  { code: 'ka', name: 'ქართული' },
  { code: 'de', name: 'Deutsch' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'gn', name: 'Guarani' },
  { code: 'gu', name: 'ગુજરાતી' },
  { code: 'ht', name: 'Kreyòl Ayisyen' },
  { code: 'ha', name: 'Hausa' },
  { code: 'haw', name: 'ʻŌlelo Hawaiʻi' },
  { code: 'iw', name: 'עברית' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'hmn', name: 'Hmoob' },
  { code: 'hu', name: 'Magyar' },
  { code: 'is', name: 'Íslenska' },
  { code: 'ig', name: 'Igbo' },
  { code: 'ilo', name: 'Ilokano' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ga', name: 'Gaeilge' },
  { code: 'it', name: 'Italiano' },
  { code: 'jv', name: 'Basa Jawa' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'kk', name: 'Қазақ тілі' },
  { code: 'km', name: 'ខ្មែរ' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'gom', name: 'कोंकणी' },
  { code: 'kri', name: 'Krio' },
  { code: 'ku', name: 'Kurdî' },
  { code: 'ckb', name: 'کوردیی ناوەندی' },
  { code: 'ky', name: 'Кыргызча' },
  { code: 'lo', name: 'ລາວ' },
  { code: 'la', name: 'Latina' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'ln', name: 'Lingála' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'lg', name: 'Luganda' },
  { code: 'lb', name: 'Lëtzebuergesch' },
  { code: 'mk', name: 'Македонски' },
  { code: 'mai', name: 'मैथिली' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'ms', name: 'Bahasa Melayu' },
  { code: 'ml', name: 'മലയാളം' },
  { code: 'mt', name: 'Malti' },
  { code: 'mi', name: 'Māori' },
  { code: 'mr', name: 'मराठी' },
  { code: 'mni-Mtei', name: 'ꯃꯤꯇꯩꯂꯣꯟ' },
  { code: 'lus', name: 'Mizo' },
  { code: 'mn', name: 'Монгол' },
  { code: 'my', name: 'မြန်မာ' },
  { code: 'ne', name: 'नेपाली' },
  { code: 'no', name: 'Norsk' },
  { code: 'ny', name: 'Chichewa' },
  { code: 'or', name: 'ଓଡ଼ିଆ' },
  { code: 'om', name: 'Oromoo' },
  { code: 'ps', name: 'پښتو' },
  { code: 'fa', name: 'فارسی' },
  { code: 'pl', name: 'Polski' },
  { code: 'pt', name: 'Português' },
  { code: 'pt-BR', name: 'Português (Brasil)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ' },
  { code: 'qu', name: 'Runasimi' },
  { code: 'ro', name: 'Română' },
  { code: 'ru', name: 'Русский' },
  { code: 'sm', name: 'Gagana Samoa' },
  { code: 'sa', name: 'संस्कृतम्' },
  { code: 'gd', name: 'Gàidhlig' },
  { code: 'nso', name: 'Sepedi' },
  { code: 'sr', name: 'Српски' },
  { code: 'st', name: 'Sesotho' },
  { code: 'sn', name: 'ChiShona' },
  { code: 'sd', name: 'سنڌي' },
  { code: 'si', name: 'සිංහල' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'so', name: 'Soomaali' },
  { code: 'es', name: 'Español' },
  { code: 'su', name: 'Basa Sunda' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'sv', name: 'Svenska' },
  { code: 'tg', name: 'Тоҷикӣ' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'tt', name: 'Татар теле' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'th', name: 'ไทย' },
  { code: 'ti', name: 'ትግርኛ' },
  { code: 'ts', name: 'Xitsonga' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'tk', name: 'Türkmençe' },
  { code: 'ak', name: 'Twi' },
  { code: 'uk', name: 'Українська' },
  { code: 'ur', name: 'اردو' },
  { code: 'ug', name: 'ئۇيغۇرچە' },
  { code: 'uz', name: 'Oʻzbekcha' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'cy', name: 'Cymraeg' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'yi', name: 'ייִדיש' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'zu', name: 'isiZulu' },
];
