# -*- coding: utf-8 -*-
import json

path = 'src/data/daiso.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

new_items = []

# ===== mask-pack (sub_kr: 마스크팩, sub_en: Mask Pack, sub_free: TRUE, sub_order: 1) =====
new_items.append({
    "sub": "mask-pack",
    "title_kr": "김정문알로에 큐어알파 알로에 하이드로겔 마스크",
    "title_en": "Kim Jung Moon Aloe Cure Alpha Aloe Hydrogel Mask",
    "desc_kr": "제주 알로에와 바쿠치올, 식물성 콜라겐을 담은 젤 타입 하이드로겔 시트로 피부에 밀착돼 진정과 탄력 케어를 동시에 돕는 신상 마스크팩. 다이소 전용으로 출시되며 '큐어알파' 라인 3종 중 하나.",
    "desc_en": "A gel-type hydrogel sheet infused with Jeju aloe, bakuchiol, and plant-based collagen that adheres closely to skin for soothing and elasticity care. Part of the 'Cure Alpha' line exclusively launched for Daiso.",
    "brand_kr": "김정문알로에",
    "price_kr": "2,000원",
    "tips_kr": "냉장 보관 후 사용하면 쿨링감과 진정 효과가 더욱 좋음. 세안 직후 부착해 10~20분 후 제거.",
    "tips_en": "Refrigerate before use for an extra cooling and soothing effect. Apply right after cleansing and remove after 10-20 minutes.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 스킨케어 코너에서 김정문알로에 큐어알파 라인 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 2,000원▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Kim Jung Moon Aloe Cure Alpha section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 2,000 KRW▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 김정문알로에 큐어알파 알로에 하이드로겔 마스크▪다이소 김정문알로에▪김정문알로에 큐어알파▪알로에 하이드로겔 마스크▪다이소 마스크팩",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪MaskPack",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "마스크팩",
    "sub_en": "Mask Pack",
    "sub_free": "TRUE",
    "sub_order": 1
})

new_items.append({
    "sub": "mask-pack",
    "title_kr": "김정문알로에 큐어알파 알로에 젤리 마스크",
    "title_en": "Kim Jung Moon Aloe Cure Alpha Aloe Jelly Mask",
    "desc_kr": "제주 알로에 성분을 담은 말랑한 젤리 텍스처 시트마스크로, 얇고 밀착력이 좋아 얼굴 굴곡에 자연스럽게 붙는 저가형 데일리 진정 마스크팩. 큐어알파 3종 라인 중 하나로 다이소 전용 출시.",
    "desc_en": "A soft jelly-textured sheet mask with Jeju aloe that clings naturally to facial contours thanks to its thin, close-fit design. An affordable daily soothing mask, part of the Cure Alpha line exclusive to Daiso.",
    "brand_kr": "김정문알로에",
    "price_kr": "1,000원",
    "tips_kr": "얇은 젤리 시트라 밀착력은 좋지만 건조가 빠른 편이므로 10분 내외로 사용 권장.",
    "tips_en": "The thin jelly sheet adheres well but dries out relatively quickly, so using it for around 10 minutes is recommended.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 스킨케어 코너에서 김정문알로에 큐어알파 라인 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 1,000원▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Kim Jung Moon Aloe Cure Alpha section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 1,000 KRW▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 김정문알로에 큐어알파 알로에 젤리 마스크▪다이소 김정문알로에▪김정문알로에 큐어알파▪알로에 젤리 마스크▪다이소 마스크팩",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪MaskPack",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "마스크팩",
    "sub_en": "Mask Pack",
    "sub_free": "TRUE",
    "sub_order": 1
})

new_items.append({
    "sub": "mask-pack",
    "title_kr": "더마펌 시카 엑소좀 카밍 리페어 패드",
    "title_en": "Dermafirm Cica Exosome Calming Repair Pad",
    "desc_kr": "더마 코스메틱 브랜드 더마펌이 다이소 전용으로 출시한 스킨케어 8종 중 하나. 72mm 대형 헤링본 패드에 시카 성분과 엑소좀을 담아 여드름성 피부 진정과 수분 케어를 동시에 잡은 신상 토너패드.",
    "desc_en": "One of 8 Daiso-exclusive skincare items from dermo-cosmetic brand Dermafirm. A large 72mm herringbone pad soaked in cica and exosome ingredients for calming acne-prone skin while delivering hydration.",
    "brand_kr": "더마펌",
    "price_kr": "5,000원",
    "tips_kr": "여드름성 피부 적합성 테스트를 마쳤으나, 자극감이 느껴지면 사용을 중단하고 패치 테스트 후 사용 권장.",
    "tips_en": "Tested suitable for acne-prone skin, but if irritation occurs, stop use and perform a patch test before continuing.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 더마펌 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Dermafirm section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50 pads)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 더마펌 시카 엑소좀 카밍 리페어 패드▪다이소 더마펌▪더마펌 시카 패드▪시카 엑소좀 패드▪다이소 마스크팩",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪MaskPack",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "마스크팩",
    "sub_en": "Mask Pack",
    "sub_free": "TRUE",
    "sub_order": 1
})

# ===== trouble-care (sub_kr: 트러블·진정 케어, sub_en: Trouble & Calming, sub_free: TRUE, sub_order: 2) =====
new_items.append({
    "sub": "trouble-care",
    "title_kr": "파티온 노스카나인 트러블패드",
    "title_en": "Pathion Nosca9 Trouble Pad",
    "desc_kr": "동아제약 파티온이 다이소 전용으로 출시한 '노스카나인 퍼스트스텝' 라인 중 하나로, 국내 최초 여드름 완화 기능성을 표방한 트러블 패드. 트러블 피부의 각질 정돈과 진정을 함께 케어.",
    "desc_en": "One of the Nosca9 First Step line items launched exclusively for Daiso by Dong-A Pharmaceutical's Pathion brand. Marketed as Korea's first acne-relief functional pad, caring for exfoliation and calming of trouble-prone skin.",
    "brand_kr": "파티온",
    "price_kr": "가격 확인 필요",
    "tips_kr": "여드름 완화 기능성 화장품으로 식약처 인증을 받았으나, 트러블이 심한 부위는 자극이 있을 수 있어 첫 사용 시 소량 테스트 권장.",
    "tips_en": "Certified as an acne-relief functional cosmetic by Korea's MFDS, but may cause irritation on severely inflamed areas, so a patch test on first use is recommended.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 파티온 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격: 매장 및 온라인몰에서 확인 필요▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Pathion section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: please check in-store or on Daiso Mall▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 파티온 노스카나인 트러블패드▪다이소 파티온▪파티온 노스카나인▪노스카나인 트러블패드▪다이소 트러블케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪TroubleCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "트러블·진정 케어",
    "sub_en": "Trouble & Calming",
    "sub_free": "TRUE",
    "sub_order": 2
})

new_items.append({
    "sub": "trouble-care",
    "title_kr": "메디필 시카 쿨링 진정 패드 2.0",
    "title_en": "Mediheal Cica Cooling Calming Pad 2.0",
    "desc_kr": "8가지 시카 성분과 판테놀을 담아 피부 온도를 낮춰주는 쿨링 진정 패드. 인체 적용 시험에서 피부 온도 4.33도 하강이 입증됐으며, 무표백 크로셀 원단으로 자극을 낮춘 다이소 인기 리뉴얼 제품.",
    "desc_en": "A cooling calming pad with 8 types of cica ingredients and panthenol that lowers skin temperature. Human trials showed a 4.33-degree skin temperature drop, using unbleached Krocell fabric for lower irritation.",
    "brand_kr": "메디필",
    "price_kr": "5,000원",
    "tips_kr": "화끈거림이나 열감이 있는 부위에 냉장 보관 후 사용하면 진정 효과가 배가됨. 50매입과 110ml 리필 타입 모두 판매.",
    "tips_en": "Refrigerating before use doubles the calming effect on flushed or overheated areas. Sold as a 50-pad pack or as a 110ml refill.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 메디필 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Mediheal section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50 pads)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 메디필 시카 쿨링 진정 패드 2.0▪다이소 메디필▪메디필 시카 패드▪시카 쿨링 진정 패드▪다이소 트러블케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪TroubleCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "트러블·진정 케어",
    "sub_en": "Trouble & Calming",
    "sub_free": "TRUE",
    "sub_order": 2
})

new_items.append({
    "sub": "trouble-care",
    "title_kr": "더마펌 글루타치온 엑소좀 잡티 토닝 패드",
    "title_en": "Dermafirm Glutathione Exosome Toning Pad",
    "desc_kr": "더마펌 다이소 전용 스킨케어 8종 중 하나로, LNP 글루타치온과 유자 엑소좀을 담아 톤 결정 및 미백 기능성을 인증받은 토닝 패드. 돌기가 있는 레이온 혼합 엠보 원단으로 각질과 노폐물 정돈까지 가능.",
    "desc_en": "One of Dermafirm's 8 Daiso-exclusive skincare items, a toning pad with LNP glutathione and citron exosome, certified for tone-brightening functionality. Its embossed rayon-blend texture also helps remove dead skin cells and residue.",
    "brand_kr": "더마펌",
    "price_kr": "5,000원",
    "tips_kr": "미백 기능성 화장품이지만 즉각적 효과보다 꾸준한 사용이 필요하며, 각질 제거 기능이 있어 매일 사용 시 피부 상태를 살펴가며 사용 권장.",
    "tips_en": "A whitening functional cosmetic that requires consistent use rather than instant results; since it also exfoliates, monitor your skin condition if using daily.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 더마펌 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Dermafirm section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50 pads)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 더마펌 글루타치온 엑소좀 잡티 토닝 패드▪다이소 더마펌▪더마펌 글루타치온 패드▪잡티 토닝 패드▪다이소 트러블케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪TroubleCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "트러블·진정 케어",
    "sub_en": "Trouble & Calming",
    "sub_free": "TRUE",
    "sub_order": 2
})

# ===== skincare (sub_kr: 스킨케어, sub_en: Skincare, sub_free: "", sub_order: 3) =====
new_items.append({
    "sub": "skincare",
    "title_kr": "더마펌 PDRN 엑소좀 포어 타이트닝 패드",
    "title_en": "Dermafirm PDRN Exosome Pore Tightening Pad",
    "desc_kr": "더마펌 다이소 전용 스킨케어 8종 중 모공 케어를 담당하는 패드. PDRN과 엑소좀 성분으로 모공을 탄탄하게 정돈해주며, 72mm 대형 사이즈로 얼굴 전체 커버가 가능한 신상 토너패드.",
    "desc_en": "A pore-care pad from Dermafirm's 8-item Daiso-exclusive skincare line. Formulated with PDRN and exosome ingredients to firm and refine pores, in a large 72mm size that covers the whole face.",
    "brand_kr": "더마펌",
    "price_kr": "5,000원",
    "tips_kr": "민감성 피부 대상 일차 자극 테스트를 완료했으나, 모공 타이트닝 성분이 강한 편이라 예민한 날에는 사용 빈도 조절 권장.",
    "tips_en": "Completed a primary irritation test for sensitive skin, but the pore-tightening ingredients are fairly strong, so adjust frequency on sensitive days.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 더마펌 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Dermafirm section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50 pads)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 더마펌 PDRN 엑소좀 포어 타이트닝 패드▪다이소 더마펌▪더마펌 포어 패드▪PDRN 엑소좀 패드▪다이소 스킨케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Skincare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "스킨케어",
    "sub_en": "Skincare",
    "sub_free": "",
    "sub_order": 3
})

new_items.append({
    "sub": "skincare",
    "title_kr": "더마펌 히알루로닉 엑소좀 플럼핑 눈가팔자 링클패치",
    "title_en": "Dermafirm Hyaluronic Exosome Plumping Eye & Nasolabial Wrinkle Patch",
    "desc_kr": "더마펌 다이소 전용 스킨케어 8종 중 눈가·팔자 부위 곡선에 맞춰 설계된 링클패치. 독점 원료 히알-리프트 펩타이드와 6종 펩타이드로 수면 중 집중 주름 케어가 가능한 신상 아이템.",
    "desc_en": "A wrinkle patch from Dermafirm's Daiso-exclusive line, shaped to fit the curves around the eyes and nasolabial folds. Formulated with the proprietary Hyal-Lift Peptide and 6 types of peptides for overnight wrinkle care.",
    "brand_kr": "더마펌",
    "price_kr": "1,000원",
    "tips_kr": "눈가 전용 소형 패치로 부위별(눈가/팔자) 곡선 설계가 다르므로, 제품 패키지에 표시된 부위에 맞게 부착 권장.",
    "tips_en": "This small patch is designed for specific facial curves (eyes vs. nasolabial folds), so apply it to the area indicated on the packaging.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 더마펌 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 1,000원(10매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Dermafirm section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 1,000 KRW (10 patches)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 더마펌 히알루로닉 엑소좀 플럼핑 눈가팔자 링클패치▪다이소 더마펌▪더마펌 링클패치▪히알루로닉 엑소좀 패치▪다이소 스킨케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Skincare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "스킨케어",
    "sub_en": "Skincare",
    "sub_free": "",
    "sub_order": 3
})

new_items.append({
    "sub": "skincare",
    "title_kr": "더마펌 피디알엔 엑소좀 링클 패치",
    "title_en": "Dermafirm PDRN Exosome Wrinkle Patch",
    "desc_kr": "더마펌 다이소 전용 스킨케어 8종 중 니들패치 2종의 하나로, 특허 공법 마이크로콘 기술을 적용해 PDRN-4D, 블랙티엑소좀, 저분자 콜라겐 성분을 각질층까지 전달하는 집중 주름 케어 패치.",
    "desc_en": "One of two needle-patch items in Dermafirm's Daiso-exclusive skincare line, using patented Microcone technology to deliver PDRN-4D, black tea exosome, and low-molecular collagen deep into the stratum corneum for intensive wrinkle care.",
    "brand_kr": "더마펌",
    "price_kr": "5,000원",
    "tips_kr": "마이크로니들 구조라 사용 중 따끔한 자극이 느껴질 수 있음. 피부가 예민하거나 트러블이 있는 부위는 사용 자제 권장.",
    "tips_en": "Since it uses a micro-needle structure, a slight tingling sensation may occur during use. Avoid use on sensitive or breakout-prone areas.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 더마펌 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(4매입)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Dermafirm section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (4 patches)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 더마펌 피디알엔 엑소좀 링클 패치▪다이소 더마펌▪더마펌 PDRN 패치▪피디알엔 엑소좀 링클패치▪다이소 스킨케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Skincare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "스킨케어",
    "sub_en": "Skincare",
    "sub_free": "",
    "sub_order": 3
})

# ===== cleanser (sub_kr: 클렌저 케어, sub_en: Cleanser, sub_free: "", sub_order: 4) =====
new_items.append({
    "sub": "cleanser",
    "title_kr": "랩잇 by 닥터지 포어 찰떡클렌저",
    "title_en": "Rapit by Dr.G Pore Chaltteok Cleanser",
    "desc_kr": "랩잇 by 닥터지 포어 클렌징 라인 중 하나로, 쫀쫀한 찰떡 텍스처와 쌀 향이 특징인 젤 클렌저. 모공 속 노폐물을 부드럽게 흡착하면서도 세안 후 당김 없이 산뜻하게 마무리되는 신상 클렌저.",
    "desc_en": "Part of the Rapit by Dr.G pore-care cleansing line, a gel cleanser with a chewy 'chaltteok' texture and rice scent. Gently draws out pore debris while leaving skin fresh without tightness after washing.",
    "brand_kr": "랩잇 by 닥터지",
    "price_kr": "5,000원",
    "tips_kr": "젤 타입이라 거품이 풍성하지 않은 편이니, 마사지하듯 충분히 문질러 사용하면 모공 클렌징 효과가 더 좋음.",
    "tips_en": "As a gel-type cleanser it doesn't lather much, so massaging it thoroughly into skin improves pore-cleansing results.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 랩잇 by 닥터지 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50ml)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Rapit by Dr.G section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50ml)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 랩잇 by 닥터지 포어 찰떡클렌저▪다이소 랩잇▪닥터지 포어 클렌저▪포어 찰떡클렌저▪다이소 클렌저",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Cleanser",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "클렌저 케어",
    "sub_en": "Cleanser",
    "sub_free": "",
    "sub_order": 4
})

new_items.append({
    "sub": "cleanser",
    "title_kr": "케어존 플러스 피케어 모공 클렌징폼",
    "title_en": "Careson Plus P-Care Pore Cleansing Foam",
    "desc_kr": "LG생활건강이 공급하는 다이소 전용 브랜드 케어존 플러스의 모공 케어 클렌징폼. 초저분자 콜라겐과 초저분자 히알루론산, 바쿠치올, 에델바이스 추출물을 함유해 세안 후에도 촉촉함을 유지.",
    "desc_en": "A pore-care cleansing foam from Careson Plus, a Daiso-exclusive brand supplied by LG Household & Health Care. Contains low-molecular collagen and hyaluronic acid, bakuchiol, and edelweiss extract to keep skin moisturized after washing.",
    "brand_kr": "케어존 플러스",
    "price_kr": "3,000원",
    "tips_kr": "미세먼지와 노폐물 세정력이 좋은 편이라 이중세안 시 첫 단계 클렌저와 함께 사용하면 더 효과적.",
    "tips_en": "Known for strong cleansing power against fine dust and impurities; using it as the second step in a double-cleansing routine works well.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 케어존 플러스 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 3,000원(100ml)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Careson Plus section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 3,000 KRW (100ml)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 케어존 플러스 피케어 모공 클렌징폼▪다이소 케어존 플러스▪LG생활건강 다이소▪피케어 모공 클렌징폼▪다이소 클렌저",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Cleanser",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "클렌저 케어",
    "sub_en": "Cleanser",
    "sub_free": "",
    "sub_order": 4
})

new_items.append({
    "sub": "cleanser",
    "title_kr": "랩잇 by 닥터지 포어 클렌징밤",
    "title_en": "Rapit by Dr.G Pore Cleansing Balm",
    "desc_kr": "랩잇 by 닥터지 포어 클렌징 라인의 오일 밤 타입 클렌저. 메이크업과 모공 속 피지까지 부드럽게 녹여내며, 물에 닿으면 우윳빛 유화가 되어 헹굼까지 산뜻한 신상 클렌징밤.",
    "desc_en": "An oil-balm cleanser from the Rapit by Dr.G pore-care cleansing line. Gently melts away makeup and pore sebum, emulsifying into a milky texture on contact with water for a refreshing rinse.",
    "brand_kr": "랩잇 by 닥터지",
    "price_kr": "5,000원",
    "tips_kr": "마스카라나 진한 메이크업도 잘 지워지는 편이라 이중세안 첫 단계로 추천. 눈가는 살살 문질러 자극을 줄일 것.",
    "tips_en": "Effectively removes even heavy makeup and mascara, making it a good first step for double cleansing. Rub gently around the eyes to minimize irritation.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 랩잇 by 닥터지 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(50ml)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Rapit by Dr.G section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (50ml)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 랩잇 by 닥터지 포어 클렌징밤▪다이소 랩잇▪닥터지 클렌징밤▪포어 클렌징밤▪다이소 클렌저",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪Cleanser",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "클렌저 케어",
    "sub_en": "Cleanser",
    "sub_free": "",
    "sub_order": 4
})

# ===== color-cosmetics (sub_kr: 색조, sub_en: Color Cosmetics, sub_free: "", sub_order: 5) =====
new_items.append({
    "sub": "color-cosmetics",
    "title_kr": "프릴루드 딘토 라벨르 로즈 립라이너",
    "title_en": "Prelude Dinto Labelle Rose Lip Liner",
    "desc_kr": "프릴루드 딘토의 '라벨르 로즈' 컬렉션 립라이너로, 실키한 텍스처와 입술 프라이밍 효과로 흐트러짐 없는 지속력을 자랑하는 신상 색조 아이템. 헤이지 로즈 등 로즈 계열 컬러로 구성.",
    "desc_en": "A lip liner from Prelude Dinto's 'Labelle Rose' collection, featuring a silky texture and lip-priming effect for smudge-free, long-lasting wear. Comes in rose-toned shades like Haze Rose.",
    "brand_kr": "프릴루드 딘토",
    "price_kr": "3,000원",
    "tips_kr": "립라이너만으로도 자연스러운 그라데이션 립 메이크업이 가능하며, 같은 컬렉션의 립틴트나 립글로스와 레이어링하면 밀착력이 더 좋아짐.",
    "tips_en": "Can create a natural gradient lip look on its own; layering with the lip tint or glass gloss from the same collection improves adherence.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 프릴루드 딘토 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 3,000원▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Prelude Dinto section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 3,000 KRW▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 프릴루드 딘토 라벨르 로즈 립라이너▪다이소 프릴루드 딘토▪라벨르 로즈 컬렉션▪딘토 립라이너▪다이소 색조",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪ColorCosmetics",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "색조",
    "sub_en": "Color Cosmetics",
    "sub_free": "",
    "sub_order": 5
})

new_items.append({
    "sub": "color-cosmetics",
    "title_kr": "입큰 퍼스널 톤 코렉팅 블러 팩트",
    "title_en": "IPKN Personal Tone Correcting Blur Pact",
    "desc_kr": "입큰 퍼스널 톤 라인의 컬러 코렉팅 팩트로, 라벤더/그린 등 색상별로 칙칙함이나 붉은기를 보정해주는 미세 구상 파우더 입자가 특징. 3,000원 가격 대비 커버력이 좋다는 후기로 화제가 된 신상.",
    "desc_en": "A color-correcting pact from IPKN's Personal Tone line, featuring fine spherical powder particles in shades like Lavender and Green to correct dullness or redness. Went viral for its strong coverage relative to its 3,000 KRW price.",
    "brand_kr": "입큰",
    "price_kr": "3,000원",
    "tips_kr": "라벤더 색상은 노랗고 칙칙한 피부톤 보정에, 그린 색상은 붉은기 보정에 적합하니 피부 고민에 맞춰 색상 선택 권장.",
    "tips_en": "The lavender shade suits correcting sallow, dull tones, while the green shade helps neutralize redness — choose based on your skin concern.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 입큰 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 3,000원(5.5g)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the IPKN section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 3,000 KRW (5.5g)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 입큰 퍼스널 톤 코렉팅 블러 팩트▪다이소 입큰▪입큰 코렉팅 팩트▪퍼스널 톤 블러 팩트▪다이소 색조",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪ColorCosmetics",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "색조",
    "sub_en": "Color Cosmetics",
    "sub_free": "",
    "sub_order": 5
})

new_items.append({
    "sub": "color-cosmetics",
    "title_kr": "태그 스킨 핏 커버 밤",
    "title_en": "TAG Skin Fit Cover Balm",
    "desc_kr": "투쿨포스쿨의 다이소 전용 브랜드 태그(TAG)가 출시한 밤 타입 커버 쿠션. 피부에 스미듯 녹아드는 멜팅밤 텍스처로 매끄러운 발림성과 함께 모공·잡티를 확실히 커버해 품절 대란을 일으킨 신상 베이스 제품.",
    "desc_en": "A balm-type cover cushion from TAG, Too Cool For School's Daiso-exclusive brand. Its melting-balm texture glides smoothly onto skin, providing solid pore and blemish coverage — it sold out repeatedly after launch.",
    "brand_kr": "태그(TAG)",
    "price_kr": "5,000원",
    "tips_kr": "밤 타입이라 소량씩 덜어 손이나 퍼프로 두드려 바르면 뭉침 없이 밀착력이 좋아짐. 라이트베이지, 내추럴베이지 등 색상 선택 가능.",
    "tips_en": "Since it's a balm type, applying a small amount at a time with fingers or a puff and patting it in prevents caking and improves adherence. Available in shades like Light Beige and Natural Beige.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 태그(TAG) 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(12g)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the TAG section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (12g)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 태그 스킨 핏 커버 밤▪다이소 태그▪TAG 커버밤▪투쿨포스쿨 다이소▪다이소 색조",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪ColorCosmetics",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "색조",
    "sub_en": "Color Cosmetics",
    "sub_free": "",
    "sub_order": 5
})

# ===== haircare (sub_kr: 헤어케어, sub_en: Hair Care, sub_free: "", sub_order: 6) =====
new_items.append({
    "sub": "haircare",
    "title_kr": "헤어테소로 잔머리 픽서카라",
    "title_en": "Hair Tesoro Flyaway Fixer Cara",
    "desc_kr": "마스카라처럼 빗 타입 브러시로 삐죽 솟은 잔머리를 슥슥 빗어 넘겨 정돈하는 헤어 스타일링 제품. 휴대가 간편해 외출 중 수시로 잔머리를 정돈할 수 있는 다이소 인기 헤어템.",
    "desc_en": "A hair styling wand with a mascara-like comb brush that smooths down flyaway hairs. Compact and portable, making it easy to touch up stray hairs on the go — a popular Daiso hair item.",
    "brand_kr": "헤어테소로",
    "price_kr": "3,000원",
    "tips_kr": "고정력은 준수하지만 떡짐 없이 자연스럽게 마무리되는 편. 소량씩 여러 번 발라 원하는 만큼 조절해서 사용 권장.",
    "tips_en": "Holds hair fairly well while finishing naturally without stiffness. Apply in small amounts multiple times to control the hold as desired.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 헤어테소로 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 3,000원▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Hair Tesoro section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 3,000 KRW▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 헤어테소로 잔머리 픽서카라▪다이소 헤어테소로▪잔머리 정리 마스카라▪헤어 픽서 카라▪다이소 헤어케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪HairCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "헤어케어",
    "sub_en": "Hair Care",
    "sub_free": "",
    "sub_order": 6
})

new_items.append({
    "sub": "haircare",
    "title_kr": "모다모다 블루비오틴 스칼프 두피가글 스케일러",
    "title_en": "Modamoda Blue Biotin Scalp Gargle Scaler",
    "desc_kr": "모다모다가 다이소 전용으로 출시한 '블루비오틴 스칼프' 탈모케어 7종 라인 중 하나. 두피를 가글하듯 헹궈내는 스케일러로, 두피 노폐물과 각질 제거를 도와주며 전 제품 식약처 인증을 받은 신상 헤어템.",
    "desc_en": "One of Modamoda's 7-item 'Blue Biotin Scalp' hair-loss care line launched exclusively for Daiso. A scaler that rinses the scalp like a gargle to remove buildup and dead skin, certified by Korea's MFDS.",
    "brand_kr": "모다모다",
    "price_kr": "5,000원",
    "tips_kr": "매일 사용을 권장하는 제품이라 소모 속도가 빠른 편. 브러시 파트가 다소 부드러워 강한 두피 마사지감을 기대하기보다 순한 세정 용도로 사용 추천.",
    "tips_en": "Recommended for daily use, so it may run out relatively quickly. The brush portion is fairly soft, so use it for gentle cleansing rather than expecting a strong massage effect.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 모다모다 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(90ml)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the Modamoda section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (90ml)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 모다모다 블루비오틴 스칼프 두피가글 스케일러▪다이소 모다모다▪블루비오틴 스칼프▪두피가글 스케일러▪다이소 헤어케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪HairCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "헤어케어",
    "sub_en": "Hair Care",
    "sub_free": "",
    "sub_order": 6
})

new_items.append({
    "sub": "haircare",
    "title_kr": "정직한실험실 트루랩 스칼프 헤어 식초",
    "title_en": "True Laboratory TrueLab Scalp Hair Vinegar",
    "desc_kr": "정직한실험실이 다이소 전용으로 선보인 헤어 식초로, 약산성 pH를 적용해 정수리 냄새와 유분 고민 관리에 도움을 주는 두피 케어템. 누적 판매 35만 개를 돌파한 다이소 스테디셀러 신상 라인.",
    "desc_en": "A hair vinegar exclusively launched for Daiso by True Laboratory, formulated at a mild acidic pH to help manage crown odor and excess oil. Has sold over 350,000 units, becoming a Daiso steady-seller.",
    "brand_kr": "정직한실험실",
    "price_kr": "5,000원",
    "tips_kr": "샴푸 후 마지막 헹굼 단계에 사용하면 두피 산도 밸런스를 맞춰주는 효과가 좋음. 식초 특유의 향이 있으나 금방 날아가는 편.",
    "tips_en": "Using it during the final rinse after shampooing helps balance scalp pH effectively. Has a slight vinegar scent that fades quickly.",
    "publish_at": "",
    "getoff_kr": "",
    "getoff_en": "",
    "direction_kr": "",
    "direction_en": "",
    "buy_kr": "🏪 전국 다이소 매장 정직한실험실 코너에서 구매 가능▪💳 다이소몰(daisomall.co.kr) 온라인 구매도 가능▪💰 가격대: 5,000원(210ml)▪⚠️ 매장별 재고가 다를 수 있으니 방문 전 다이소몰 재고 확인 추천▪📌 매장 및 홈페이지/웹사이트 현황에 따라 언어가 지원됨",
    "buy_en": "🏪 Available at the True Laboratory section in Daiso stores nationwide▪💳 Also purchasable online via Daiso Mall (daisomall.co.kr)▪💰 Price: 5,000 KRW (210ml)▪⚠️ Stock varies by branch, so checking Daiso Mall inventory beforehand is recommended▪📌 Language support varies by store and website/homepage availability",
    "keywords_kr": "다이소 정직한실험실 트루랩 스칼프 헤어 식초▪다이소 정직한실험실▪트루랩 헤어식초▪스칼프 헤어 식초▪다이소 헤어케어",
    "hashtags": "Daiso▪DaisoKorea▪DaisoHaul▪KBeauty▪HairCare",
    "web": "https://www.daisomall.co.kr/",
    "sub_kr": "헤어케어",
    "sub_en": "Hair Care",
    "sub_free": "",
    "sub_order": 6
})

assert len(new_items) == 18, f"Expected 18 items, got {len(new_items)}"

data.extend(new_items)

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Added", len(new_items), "items. New total:", len(data))
